name: Release App

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Flutter Doctor
        run: flutter doctor -v
        
      - name: Build Android
        run: flutter build apk --release --verbose
      
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: |
          flutter build ipa --release
          cd build/ios/iphoneos
          zip -r app-release.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/iphoneos/app-release.ipa 

  create-release:
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest
    steps:
      - name: Download Android Artifact
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: artifacts/android

      - name: Download iOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: ios-ipa
          path: artifacts/ios
        continue-on-error: true

      - name: Generate version
        id: version
        run: |
          echo "version=$(date +'%Y%m%d')-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Create APK Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}-apk
          name: APKRelease ${{ steps.version.outputs.version }}
          files: |
            artifacts/android/app-release.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create IPA Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}-ipa
          name: IPA Release ${{ steps.version.outputs.version }}
          files: |
            artifacts/ios/app-release.ipa
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true